# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMYtQ97x6fWLOvWcbGpJxJggUeRCBcim
"""

name = input("Type your name")
print("welcome",name,"to this adventure!")

answer = input("you are on dirt road,it has to come to an end and you can go to left or right .which way would you like to go?")

if answer == "left":
  answer =input("You come to a river ,you can walk around or swim across? type walk or swim :")

  if answer == "swim":
    print("You swam across and were eaten by an alligator")

  elif answer == "walk":
     print("You walked for many miles,ran out of water and you lost the game.")
     
  else:
    print("Not a valid option, You lose")

elif answer =="right":
  answer = input("You come to the bridge, it looks wobbly, do you want to cross it or head back")

  if answer =="back":
    print("You go back and lose")

  elif answer == "cross":
    answer = input("You cross the bridge and met the stranger. Do you want to talk with them(yes/no) :")

    if answer =="yes":
      print ("you talk to the stranger and he give you the gold. You Won!")

    elif answer =="no":
      print("You ignore the stranger and they are offended. You lose.")

    else:
      print("NOt a valid option. You lose.")
  else:
      print("NOt a valid option. You lose.")
else:
      print("NOt a valid option. You lose.")